# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d975072bf1b5ba0b133636e6bb0aef24269b238049134c7217cc0750ee3f39125d9633ad209693c4a256f8a09cd57fa6f1c0b5e631540c5a90a81718425c6492

test:
  secret_key_base: 2a69f379272c7ae7d37fd3c609b2dd3cb06e3c67864e1bbef4f36cfd3935f403dd020bb3cdfe0ca9eb9d97365ab69b17ee4a8a07e60f6ed9dff79adca17aa791

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
